## Example - Fit TransE from CSVs in disk
* put the training and validation CSVs in seprate folders like:  
└──train_data  
        ├───train_1.csv  
        ├───train_2.csv  
└──valid_data  
        ├───valid_1.csv  
        ├───valid_2.csv  
* each csv file store 3 columns with (h,r,t) repectively (with no header).
* you can split the data into multiple CSVs. 

In [1]:
from KGE.TransE import TransE

In [2]:
model = TransE(embedding_size = 100, negative_ratio = 10, corrupt_side = 'h+t', margin = 0.5, norm = 2, batch_corrupt = True)

In [3]:
model.fit(train_X = "data/fb15k_237_train", val_X = "data/fb15k_237_valid", epochs = 20, learning_rate = 0.001, batch_count = 100,
          early_stopping = None, log_path = "tensorboard/TransE_logs")

INFO:root:[2020-09-09 18:55:57.062945] Preprocessing training triplet...
INFO:root:[2020-09-09 18:55:57.677173] Initialize Embeddings...
INFO:root:[2020-09-09 18:55:57.684164] Start Training...
epoch: 19, train loss: 0.024528, valid loss: 0.037821: 100%|██████████| 20/20 [05:16<00:00, 15.82s/it]


### Get Entities & Relations Embeddings

In [4]:
model.get_embeddings(['/m/027rn', '/m/06cx9'], embedding_type = 'entity')

array([[-0.04433256, -0.17493737, -0.15591688,  0.04056852, -0.09089171,
        -0.07912163,  0.03474689,  0.15898398,  0.150213  , -0.11283677,
         0.03728622,  0.10838893,  0.1017431 , -0.026868  ,  0.14073792,
        -0.13027509,  0.03504661,  0.10883214, -0.13251556, -0.18425453,
        -0.09046879, -0.04345833, -0.02855208,  0.14018781,  0.22457458,
         0.05537203, -0.03128373,  0.10077996,  0.03728304, -0.1406233 ,
        -0.08404887, -0.03968583,  0.12828548,  0.0339542 , -0.09423982,
         0.16179712,  0.07182038, -0.08429069, -0.04872237,  0.05074064,
        -0.08736536, -0.06665482,  0.15172175,  0.0320746 , -0.11772228,
         0.1401052 ,  0.09355219,  0.17303786, -0.00050522,  0.210382  ,
         0.04339588, -0.14609516, -0.09212832,  0.0056595 ,  0.2545179 ,
         0.07527926, -0.18581122,  0.19840293,  0.15205744, -0.07622391,
        -0.13836691,  0.11174433, -0.03868292, -0.03264686,  0.08910865,
         0.07501779, -0.07740796, -0.16403764, -0.0

In [5]:
model.get_embeddings(['/location/country/form_of_government'], embedding_type = 'relation')

array([[ 0.17536214,  0.11498808,  0.26552436,  0.15539597,  0.17944202,
        -0.01281165,  0.18916929,  0.0061124 , -0.10598401,  0.18266352,
        -0.09038032, -0.02138694, -0.20029911,  0.17160851, -0.0064995 ,
        -0.00677435,  0.06493562, -0.17669371,  0.25101805,  0.27390635,
         0.17558819,  0.2349753 ,  0.01315945,  0.02189637, -0.32059684,
         0.05932235,  0.16877875,  0.01193699,  0.06152887,  0.20136909,
         0.08118254, -0.04933951, -0.11871526, -0.16707268, -0.03127211,
        -0.23704672, -0.13372345,  0.01986436, -0.09853824,  0.01330855,
        -0.11188354,  0.17154299, -0.19063637, -0.21155499,  0.15446085,
        -0.03097828, -0.01398807,  0.00800423, -0.1263265 , -0.04188505,
        -0.16649154,  0.26864064,  0.01338554,  0.19668919, -0.26765814,
        -0.02364636,  0.31473708,  0.01348936, -0.23726721,  0.24971965,
         0.0721427 , -0.04442139, -0.01122312, -0.18770291, -0.16007502,
        -0.15705977,  0.18173578, -0.03129192, -0.0

### Get All Entities & Relations Embeddings

In [6]:
# entities embeddings
model.ent_emb.numpy()

array([[ 0.14059348,  0.08235925, -0.12740146, ...,  0.00669367,
        -0.07217453,  0.12388209],
       [ 0.02632413,  0.09181372, -0.0963528 , ...,  0.03060952,
        -0.12859109,  0.11586931],
       [ 0.00043591, -0.1603149 , -0.07471798, ...,  0.06274986,
        -0.06321405, -0.06286403],
       ...,
       [-0.20838852,  0.00821889,  0.03450869, ..., -0.03865098,
        -0.18429   , -0.03541154],
       [ 0.11678603, -0.05030166, -0.14026417, ..., -0.13259949,
         0.02838923,  0.15154475],
       [-0.03415262,  0.06427687,  0.1156728 , ...,  0.10849107,
         0.00247433, -0.0780201 ]], dtype=float32)

In [7]:
# relations embeddings
model.rel_emb.numpy()

array([[ 0.22122599, -0.16368595, -0.19892941, ...,  0.1593274 ,
         0.1402985 ,  0.04958722],
       [ 0.09419548,  0.19979738, -0.19789302, ..., -0.0238177 ,
         0.18317473,  0.27955082],
       [-0.1962291 , -0.19018427,  0.11395627, ..., -0.22741817,
         0.14410055,  0.13695306],
       ...,
       [-0.12117118, -0.11929075,  0.10740736, ...,  0.00787964,
         0.03663487, -0.02768844],
       [ 0.08228766, -0.0214036 , -0.19921705, ..., -0.03056948,
         0.09556547,  0.16867003],
       [ 0.13226622, -0.02123455, -0.28177258, ...,  0.04508905,
        -0.13101278,  0.27782527]], dtype=float32)

### Get Entities & Relations Dictionary

In [8]:
model.dict_ent2id

{'/m/015ynm': 0,
 '/m/0dp7wt': 1,
 '/m/01z8f0': 2,
 '/m/0m491': 3,
 '/m/012201': 4,
 '/m/0906w9': 5,
 '/m/07_pf': 6,
 '/m/0g0vx': 7,
 '/m/023mdt': 8,
 '/m/0kjrx': 9,
 '/m/030qb3t': 10,
 '/m/0138mv': 11,
 '/m/03v0t': 12,
 '/m/06mr6': 13,
 '/m/07ldhs': 14,
 '/m/01vxqyl': 15,
 '/m/0gwgn1k': 16,
 '/m/01jqr_5': 17,
 '/m/05j0wc': 18,
 '/m/06f32': 19,
 '/m/046n4q': 20,
 '/m/0882r_': 21,
 '/m/0gq6s3': 22,
 '/m/0bvzp': 23,
 '/m/01nfys': 24,
 '/m/0fj9f': 25,
 '/m/02psgq': 26,
 '/m/03dhbp': 27,
 '/m/018gqj': 28,
 '/m/016vqk': 29,
 '/m/03zw80': 30,
 '/m/05btx9': 31,
 '/m/0fw9n7': 32,
 '/m/051n13': 33,
 '/m/03z9585': 34,
 '/m/01817f': 35,
 '/m/01r4k': 36,
 '/m/044l47': 37,
 '/m/01wrcxr': 38,
 '/m/02z3cm0': 39,
 '/m/02lhm2': 40,
 '/m/0l4vc': 41,
 '/m/07sc6nw': 42,
 '/m/01k2yr': 43,
 '/m/05y0cr': 44,
 '/m/01dhmw': 45,
 '/m/034np8': 46,
 '/m/0dmy0': 47,
 '/m/0g7pm': 48,
 '/m/019mdt': 49,
 '/m/023b97': 50,
 '/m/0g5ff': 51,
 '/m/02kxbx3': 52,
 '/m/0443xn': 53,
 '/m/09qgm': 54,
 '/m/01kgxf': 55,
 '/m/0mw

In [9]:
model.dict_rel2id

{'/government/politician/government_positions_held./government/government_position_held/basic_title': 0,
 '/award/award_nominee/award_nominations./award/award_nomination/award': 1,
 '/sports/sports_team/roster./american_football/football_roster_position/position': 2,
 '/sports/sports_team/roster./basketball/basketball_roster_position/position': 3,
 '/broadcast/content/artist': 4,
 '/base/biblioness/bibs_location/country': 5,
 '/film/film_distributor/films_distributed./film/film_film_distributor_relationship/film': 6,
 '/base/marchmadness/ncaa_basketball_tournament/seeds./base/marchmadness/ncaa_tournament_seed/team': 7,
 '/user/alexander/philosophy/philosopher/interests': 8,
 '/baseball/baseball_team/team_stats./baseball/baseball_team_stats/season': 9,
 '/base/biblioness/bibs_location/state': 10,
 '/influence/influence_node/peers./influence/peer_relationship/peers': 11,
 '/award/award_winning_work/awards_won./award/award_honor/award': 12,
 '/music/artist/track_contributions./music/track

In [10]:
model.dict_id2ent

['/m/015ynm',
 '/m/0dp7wt',
 '/m/01z8f0',
 '/m/0m491',
 '/m/012201',
 '/m/0906w9',
 '/m/07_pf',
 '/m/0g0vx',
 '/m/023mdt',
 '/m/0kjrx',
 '/m/030qb3t',
 '/m/0138mv',
 '/m/03v0t',
 '/m/06mr6',
 '/m/07ldhs',
 '/m/01vxqyl',
 '/m/0gwgn1k',
 '/m/01jqr_5',
 '/m/05j0wc',
 '/m/06f32',
 '/m/046n4q',
 '/m/0882r_',
 '/m/0gq6s3',
 '/m/0bvzp',
 '/m/01nfys',
 '/m/0fj9f',
 '/m/02psgq',
 '/m/03dhbp',
 '/m/018gqj',
 '/m/016vqk',
 '/m/03zw80',
 '/m/05btx9',
 '/m/0fw9n7',
 '/m/051n13',
 '/m/03z9585',
 '/m/01817f',
 '/m/01r4k',
 '/m/044l47',
 '/m/01wrcxr',
 '/m/02z3cm0',
 '/m/02lhm2',
 '/m/0l4vc',
 '/m/07sc6nw',
 '/m/01k2yr',
 '/m/05y0cr',
 '/m/01dhmw',
 '/m/034np8',
 '/m/0dmy0',
 '/m/0g7pm',
 '/m/019mdt',
 '/m/023b97',
 '/m/0g5ff',
 '/m/02kxbx3',
 '/m/0443xn',
 '/m/09qgm',
 '/m/01kgxf',
 '/m/0mwh1',
 '/m/0l9k1',
 '/m/047sxrj',
 '/m/03bdv',
 '/m/046b0s',
 '/m/02w7gg',
 '/m/0gj8nq2',
 '/m/018q7',
 '/m/09cdxn',
 '/m/015y2q',
 '/m/098s1',
 '/m/02yv_b',
 '/m/029skd',
 '/m/01n8_g',
 '/m/01nx_8',
 '/m/01qkqwg',


In [11]:
model.dict_id2rel

['/government/politician/government_positions_held./government/government_position_held/basic_title',
 '/award/award_nominee/award_nominations./award/award_nomination/award',
 '/sports/sports_team/roster./american_football/football_roster_position/position',
 '/sports/sports_team/roster./basketball/basketball_roster_position/position',
 '/broadcast/content/artist',
 '/base/biblioness/bibs_location/country',
 '/film/film_distributor/films_distributed./film/film_film_distributor_relationship/film',
 '/base/marchmadness/ncaa_basketball_tournament/seeds./base/marchmadness/ncaa_tournament_seed/team',
 '/user/alexander/philosophy/philosopher/interests',
 '/baseball/baseball_team/team_stats./baseball/baseball_team_stats/season',
 '/base/biblioness/bibs_location/state',
 '/influence/influence_node/peers./influence/peer_relationship/peers',
 '/award/award_winning_work/awards_won./award/award_honor/award',
 '/music/artist/track_contributions./music/track_contribution/role',
 '/sports/sports_team