## Example - Fit TransE from np.array

In [1]:
import numpy as np

In [2]:
train = np.loadtxt("data/fb15k_237_train/fb15k_237_train.csv", dtype = str, delimiter = ',')
valid = np.loadtxt("data/fb15k_237_valid/fb15k_237_valid.csv", dtype = str, delimiter = ',')

In [3]:
train

array([['/m/027rn', '/location/country/form_of_government', '/m/06cx9'],
       ['/m/017dcd',
        '/tv/tv_program/regular_cast./tv/regular_tv_appearance/actor',
        '/m/06v8s0'],
       ['/m/07s9rl0', '/media_common/netflix_genre/titles', '/m/0170z3'],
       ...,
       ['/m/0djvzd',
        '/soccer/football_player/current_team./sports/sports_team_roster/team',
        '/m/02b16p'],
       ['/m/0gmblvq',
        '/award/award_winning_work/awards_won./award/award_honor/award',
        '/m/07kjk7c'],
       ['/m/020jqv',
        '/award/award_nominee/award_nominations./award/award_nomination/nominated_for',
        '/m/09d3b7']], dtype='<U146')

In [4]:
valid

array([['/m/07pd_j', '/film/film/genre', '/m/02l7c8'],
       ['/m/06wxw', '/location/location/time_zones', '/m/02fqwt'],
       ['/m/01t94_1',
        '/people/person/spouse_s./people/marriage/type_of_union',
        '/m/04ztj'],
       ...,
       ['/m/01j4ls', '/common/topic/webpage./common/webpage/category',
        '/m/08mbj5d'],
       ['/m/0cmdwwg',
        '/film/film/release_date_s./film/film_regional_release_date/film_release_region',
        '/m/06t2t'],
       ['/m/0gs6vr', '/film/actor/film./film/performance/film',
        '/m/0gj96ln']], dtype='<U146')

In [5]:
from KGE.TransE import TransE

In [6]:
model = TransE(embedding_size = 100, negative_ratio = 10, corrupt_side = 'h+t', margin = 0.5, norm = 2, batch_corrupt = True)

In [7]:
model.fit(train_X = train, val_X = valid, epochs = 10, learning_rate = 0.001, batch_count = 100,
          early_stopping = None, log_path = "tensorboard/TransE_logs")

INFO:root:[2020-09-09 18:55:56.296185] Preprocessing training triplet...
INFO:root:[2020-09-09 18:55:58.978664] Initialize Embeddings...
INFO:root:[2020-09-09 18:55:58.986642] Start Training...
epoch: 9, train loss: 0.034986, valid loss: 0.044723: 100%|██████████| 10/10 [02:09<00:00, 12.94s/it]


### Get Entities & Relations Embeddings

In [8]:
model.get_embeddings(['/m/027rn', '/m/06cx9'], embedding_type = 'entity')

array([[ 0.0815158 ,  0.11250611, -0.08748357,  0.09922931,  0.03308614,
        -0.09949072,  0.15120652, -0.03542741, -0.07088157,  0.08159415,
        -0.08235645,  0.10113566,  0.07907211,  0.03640964, -0.10112389,
        -0.11517132,  0.08811218,  0.11531864,  0.1606466 , -0.0737868 ,
         0.07200435,  0.05714055,  0.06248849, -0.00140948, -0.02574959,
        -0.13865843, -0.03845841,  0.0907652 , -0.08242508,  0.04729021,
        -0.09296423,  0.01709962, -0.00096745, -0.09045409, -0.07267908,
         0.11539435, -0.01453623,  0.04098032, -0.04166685,  0.06945375,
         0.01259372, -0.0018287 ,  0.09841402, -0.12230895,  0.02429687,
        -0.13242543, -0.06106193, -0.03023333, -0.12217302,  0.02534984,
         0.06990279, -0.02818092, -0.12799537,  0.06617494,  0.08391473,
         0.08051478, -0.04165189,  0.0137433 ,  0.08860323, -0.00664633,
        -0.09231256,  0.07213911,  0.12601002, -0.03551336,  0.10466606,
        -0.05214097,  0.12367085,  0.09895423,  0.1

In [9]:
model.get_embeddings(['/location/country/form_of_government'], embedding_type = 'relation')

array([[-0.18433315, -0.16693722,  0.00899832, -0.21477966, -0.15826681,
        -0.00461072, -0.03418408, -0.05162477, -0.00396141, -0.1322573 ,
         0.17493327, -0.1810933 ,  0.03893385, -0.11947341,  0.2214399 ,
        -0.00728584, -0.06087051, -0.04604998, -0.0132931 ,  0.16861862,
         0.01997564,  0.02789003, -0.23096828,  0.04078789,  0.13448828,
         0.04925731, -0.01164521, -0.1781353 ,  0.19260757, -0.16512042,
         0.21772508, -0.08347488,  0.07465072,  0.01554114,  0.17445491,
        -0.16406296,  0.08183002, -0.14367388,  0.11132981, -0.07011338,
         0.03143564, -0.04074896, -0.2384202 ,  0.23603348, -0.12256699,
         0.17860092, -0.02478736, -0.09696538,  0.14890939,  0.01682127,
        -0.00494629, -0.07650258,  0.013646  , -0.01029745, -0.01590945,
        -0.04080667,  0.06424354,  0.1024584 , -0.17607386, -0.1652393 ,
         0.18640856,  0.06117325, -0.20294154,  0.19191344, -0.14268668,
         0.16330436, -0.01860248, -0.2319042 , -0.0

### Get All Entities & Relations Embeddings

In [10]:
# entities embeddings
model.ent_emb.numpy()

array([[ 0.01441636,  0.07977753, -0.01064893, ..., -0.02100465,
        -0.05430459, -0.01883129],
       [-0.00361612,  0.12032679,  0.01424943, ..., -0.03298898,
        -0.03312665, -0.05126744],
       [ 0.01279771,  0.07130551, -0.00100307, ..., -0.00563994,
        -0.07446473, -0.02303449],
       ...,
       [ 0.04572886,  0.06451509,  0.01228793, ..., -0.03408512,
        -0.07557768, -0.01963659],
       [ 0.08299762,  0.06089311, -0.02115597, ..., -0.02474995,
        -0.08299822, -0.03194607],
       [ 0.00507923,  0.05500428,  0.07496195, ...,  0.00581421,
        -0.06419884, -0.03028463]], dtype=float32)

In [11]:
# relations embeddings
model.rel_emb.numpy()

array([[ 0.21498103,  0.12339763,  0.06336352, ..., -0.1038327 ,
        -0.02958801,  0.01299879],
       [-0.0688275 ,  0.11370452, -0.1421391 , ...,  0.0372499 ,
         0.08657318,  0.00653091],
       [-0.0877726 ,  0.24549063,  0.01833364, ...,  0.01764442,
         0.05022673, -0.05134317],
       ...,
       [ 0.06841665, -0.07575443, -0.05541715, ..., -0.09379929,
        -0.05038961, -0.00333597],
       [ 0.13118617,  0.12155947, -0.22497603, ...,  0.05320301,
        -0.06377999, -0.07712759],
       [ 0.06149041, -0.24570292,  0.19012159, ...,  0.10707929,
         0.08641836, -0.2237697 ]], dtype=float32)

### Get Entities & Relations Dictionary

In [13]:
model.dict_ent2id

{'/m/010016': 0,
 '/m/0100mt': 1,
 '/m/0102t4': 2,
 '/m/0104lr': 3,
 '/m/0105y2': 4,
 '/m/0106dv': 5,
 '/m/0108xl': 6,
 '/m/0109vk': 7,
 '/m/010bnr': 8,
 '/m/010bxh': 9,
 '/m/010cw1': 10,
 '/m/010dft': 11,
 '/m/010h9y': 12,
 '/m/010hn': 13,
 '/m/010m55': 14,
 '/m/010nlt': 15,
 '/m/010p3': 16,
 '/m/010r6f': 17,
 '/m/010rvx': 18,
 '/m/010t4v': 19,
 '/m/010tkc': 20,
 '/m/010v8k': 21,
 '/m/010xjr': 22,
 '/m/010y34': 23,
 '/m/010z5n': 24,
 '/m/0113sg': 25,
 '/m/0114m0': 26,
 '/m/0118d3': 27,
 '/m/011_3s': 28,
 '/m/011_6p': 29,
 '/m/011_vz': 30,
 '/m/011hdn': 31,
 '/m/011hq1': 32,
 '/m/011j5x': 33,
 '/m/011k11': 34,
 '/m/011k1h': 35,
 '/m/011k4g': 36,
 '/m/011k_j': 37,
 '/m/011kn2': 38,
 '/m/011lpr': 39,
 '/m/011lvx': 40,
 '/m/011pcj': 41,
 '/m/011s0': 42,
 '/m/011s9r': 43,
 '/m/011v3': 44,
 '/m/011vx3': 45,
 '/m/011w20': 46,
 '/m/011w4n': 47,
 '/m/011w54': 48,
 '/m/011wdm': 49,
 '/m/011wtv': 50,
 '/m/011x_4': 51,
 '/m/011xg5': 52,
 '/m/011xhx': 53,
 '/m/011xjd': 54,
 '/m/011xy1': 55,
 '/m/0

In [14]:
model.dict_rel2id

{'/american_football/football_team/current_roster./sports/sports_team_roster/position': 0,
 '/award/award_category/category_of': 1,
 '/award/award_category/disciplines_or_subjects': 2,
 '/award/award_category/nominees./award/award_nomination/nominated_for': 3,
 '/award/award_category/winners./award/award_honor/award_winner': 4,
 '/award/award_category/winners./award/award_honor/ceremony': 5,
 '/award/award_ceremony/awards_presented./award/award_honor/award_winner': 6,
 '/award/award_ceremony/awards_presented./award/award_honor/honored_for': 7,
 '/award/award_nominated_work/award_nominations./award/award_nomination/nominated_for': 8,
 '/award/award_nominee/award_nominations./award/award_nomination/award': 9,
 '/award/award_nominee/award_nominations./award/award_nomination/award_nominee': 10,
 '/award/award_nominee/award_nominations./award/award_nomination/nominated_for': 11,
 '/award/award_winner/awards_won./award/award_honor/award_winner': 12,
 '/award/award_winning_work/awards_won./aw

In [15]:
model.dict_id2ent

['/m/010016',
 '/m/0100mt',
 '/m/0102t4',
 '/m/0104lr',
 '/m/0105y2',
 '/m/0106dv',
 '/m/0108xl',
 '/m/0109vk',
 '/m/010bnr',
 '/m/010bxh',
 '/m/010cw1',
 '/m/010dft',
 '/m/010h9y',
 '/m/010hn',
 '/m/010m55',
 '/m/010nlt',
 '/m/010p3',
 '/m/010r6f',
 '/m/010rvx',
 '/m/010t4v',
 '/m/010tkc',
 '/m/010v8k',
 '/m/010xjr',
 '/m/010y34',
 '/m/010z5n',
 '/m/0113sg',
 '/m/0114m0',
 '/m/0118d3',
 '/m/011_3s',
 '/m/011_6p',
 '/m/011_vz',
 '/m/011hdn',
 '/m/011hq1',
 '/m/011j5x',
 '/m/011k11',
 '/m/011k1h',
 '/m/011k4g',
 '/m/011k_j',
 '/m/011kn2',
 '/m/011lpr',
 '/m/011lvx',
 '/m/011pcj',
 '/m/011s0',
 '/m/011s9r',
 '/m/011v3',
 '/m/011vx3',
 '/m/011w20',
 '/m/011w4n',
 '/m/011w54',
 '/m/011wdm',
 '/m/011wtv',
 '/m/011x_4',
 '/m/011xg5',
 '/m/011xhx',
 '/m/011xjd',
 '/m/011xy1',
 '/m/011ycb',
 '/m/011yd2',
 '/m/011ydl',
 '/m/011yfd',
 '/m/011yg9',
 '/m/011yhm',
 '/m/011ykb',
 '/m/011yl_',
 '/m/011yn5',
 '/m/011yph',
 '/m/011ypx',
 '/m/011yqc',
 '/m/011yr9',
 '/m/011yrp',
 '/m/011ys5',
 '/m/011ys

In [16]:
model.dict_id2rel

['/american_football/football_team/current_roster./sports/sports_team_roster/position',
 '/award/award_category/category_of',
 '/award/award_category/disciplines_or_subjects',
 '/award/award_category/nominees./award/award_nomination/nominated_for',
 '/award/award_category/winners./award/award_honor/award_winner',
 '/award/award_category/winners./award/award_honor/ceremony',
 '/award/award_ceremony/awards_presented./award/award_honor/award_winner',
 '/award/award_ceremony/awards_presented./award/award_honor/honored_for',
 '/award/award_nominated_work/award_nominations./award/award_nomination/nominated_for',
 '/award/award_nominee/award_nominations./award/award_nomination/award',
 '/award/award_nominee/award_nominations./award/award_nomination/award_nominee',
 '/award/award_nominee/award_nominations./award/award_nomination/nominated_for',
 '/award/award_winner/awards_won./award/award_honor/award_winner',
 '/award/award_winning_work/awards_won./award/award_honor/award',
 '/award/award_win